project:
  type: website
  output-dir: docs

website:
  title: "ISLR Exercises"
  navbar:
    left:
      - text: "Home"
        href: index.html
      - text: "Linear Regression"
        href: "Linear regression/Linear Regression.html"

format:
  html:
    theme: cosmo
    toc: true
    code-fold: true
    self-contained: true
